# Generated by Django 5.2.17 on 2026-09-25 14:03

import django.db.models.deletion
import django.db.models.functions.text
import liikkeet.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Liike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nimi", models.CharField(max_length=200)),
                ("y_tunnus", models.CharField(blank=True, max_length=20)),
                (
                    "alv_prosentti",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("25.5"), max_digits=5
                    ),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "liike",
                "verbose_name_plural": "liikkeet",
            },
        ),
        migrations.CreateModel(
            name="Kayttaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("sahkoposti", models.EmailField(max_length=254, unique=True)),
                ("nimi", models.CharField(max_length=200)),
                (
                    "rooli",
                    models.CharField(
                        choices=[
                            ("admin", "Ylläpitäjä"),
                            ("osto", "Osto"),
                            ("myynti", "Myynti"),
                            ("kunnostus", "Kunnostus / piha"),
                            ("talous", "Talous"),
                        ],
                        default="myynti",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktiivinen"),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "liike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kayttajat",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "käyttäjä",
                "verbose_name_plural": "käyttäjät",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("sahkoposti"),
                        name="kayttaja_sahkoposti_uniikki_pienet",
                    )
                ],
            },
            managers=[
                ("objects", liikkeet.models.KayttajaManager()),
            ],
        ),
    ]
