# Generated by Django 5.2.17 on 2026-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liikkeet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kayttaja",
            name="nayta_brutto",
            field=models.BooleanField(default=False, verbose_name="luvut bruttona"),
        ),
    ]
