# Generated by Django 5.2.17 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liikkeet", "0002_kayttaja_nayta_brutto"),
    ]

    operations = [
        migrations.AddField(
            model_name="liike",
            name="lahiosoite",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="lähiosoite"
            ),
        ),
        migrations.AddField(
            model_name="liike",
            name="myyntiehdot",
            field=models.TextField(blank=True, verbose_name="myyntisopimuksen ehdot"),
        ),
        migrations.AddField(
            model_name="liike",
            name="ostoehdot",
            field=models.TextField(blank=True, verbose_name="ostosopimuksen ehdot"),
        ),
        migrations.AddField(
            model_name="liike",
            name="postinumero",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="postinumero"
            ),
        ),
        migrations.AddField(
            model_name="liike",
            name="postitoimipaikka",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="postitoimipaikka"
            ),
        ),
        migrations.AddField(
            model_name="liike",
            name="puhelin",
            field=models.CharField(blank=True, max_length=50, verbose_name="puhelin"),
        ),
        migrations.AddField(
            model_name="liike",
            name="sahkoposti",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="sähköposti"
            ),
        ),
        migrations.AddField(
            model_name="liike",
            name="tilinumero",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="tilinumero (IBAN)"
            ),
        ),
    ]
