# Generated by Django 5.2.17 on 2026-09-25 14:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liikkeet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ajoneuvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rekisterinumero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="rekisterinumero"
                    ),
                ),
                (
                    "vin",
                    models.CharField(blank=True, max_length=17, verbose_name="VIN"),
                ),
                ("merkki", models.CharField(max_length=100, verbose_name="merkki")),
                ("malli", models.CharField(max_length=100, verbose_name="malli")),
                (
                    "mallitarkenne",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="mallitarkenne"
                    ),
                ),
                (
                    "vuosimalli",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="vuosimalli"
                    ),
                ),
                (
                    "ensirekisterointi",
                    models.DateField(
                        blank=True, null=True, verbose_name="ensirekisteröinti"
                    ),
                ),
                (
                    "kayttovoima",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="käyttövoima"
                    ),
                ),
                (
                    "vaihteisto",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="vaihteisto"
                    ),
                ),
                (
                    "korimalli",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="korimalli"
                    ),
                ),
                (
                    "vari",
                    models.CharField(blank=True, max_length=50, verbose_name="väri"),
                ),
                (
                    "teho_kw",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="teho (kW)"
                    ),
                ),
                (
                    "iskutilavuus",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="iskutilavuus (cm³)"
                    ),
                ),
                (
                    "vetotapa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etuveto", "Etuveto"),
                            ("takaveto", "Takaveto"),
                            ("neliveto", "Neliveto"),
                        ],
                        max_length=20,
                        verbose_name="vetotapa",
                    ),
                ),
                (
                    "ovet",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ovet"
                    ),
                ),
                (
                    "istuimet",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="istuimet"
                    ),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "ajoneuvo",
                "verbose_name_plural": "ajoneuvot",
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Kierto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="kilometrit"
                    ),
                ),
                (
                    "tila",
                    models.CharField(
                        choices=[
                            ("tarjottu", "Tarjottu"),
                            ("ostettu", "Ostettu"),
                            ("tulossa", "Tulossa"),
                            ("kunnostuksessa", "Kunnostuksessa"),
                            ("myynnissa", "Myynnissä"),
                            ("varattu", "Varattu"),
                            ("myyty", "Myyty"),
                            ("toimitettu", "Toimitettu"),
                            ("hylatty", "Hylätty"),
                        ],
                        default="tarjottu",
                        max_length=20,
                        verbose_name="tila",
                    ),
                ),
                (
                    "tila_muutettu",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sijainti",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="sijainti"
                    ),
                ),
                (
                    "ostokanava",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rahoitusyhtio", "Rahoitusyhtiö"),
                            ("huutokauppa", "Huutokauppa"),
                            ("autoliike", "Autoliike"),
                            ("yksityinen", "Yksityinen"),
                            ("muu", "Muu"),
                        ],
                        max_length=20,
                        verbose_name="ostokanava",
                    ),
                ),
                (
                    "tarjottu_hinta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="pyydetty hinta",
                    ),
                ),
                (
                    "tarjottu_pvm",
                    models.DateField(blank=True, null=True, verbose_name="tarjottu"),
                ),
                (
                    "hylkayksen_syy",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="hylkäyksen syy"
                    ),
                ),
                (
                    "ostohinta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="ostohinta",
                    ),
                ),
                (
                    "ostopvm",
                    models.DateField(blank=True, null=True, verbose_name="ostopäivä"),
                ),
                (
                    "alv_kasittely",
                    models.CharField(
                        choices=[
                            ("marginaali", "Marginaaliverotus"),
                            ("alv", "Normaali ALV"),
                        ],
                        default="marginaali",
                        max_length=20,
                        verbose_name="verokohtelu",
                    ),
                ),
                (
                    "arvioitu_saapuminen",
                    models.DateField(
                        blank=True, null=True, verbose_name="arvioitu saapuminen"
                    ),
                ),
                (
                    "pyyntihinta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="pyyntihinta",
                    ),
                ),
                (
                    "myyntihinta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="myyntihinta",
                    ),
                ),
                (
                    "myyntipvm",
                    models.DateField(blank=True, null=True, verbose_name="myyntipäivä"),
                ),
                (
                    "laskunumero",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="laskunumero"
                    ),
                ),
                (
                    "maksettu_pvm",
                    models.DateField(blank=True, null=True, verbose_name="maksettu"),
                ),
                (
                    "toimitettu_pvm",
                    models.DateField(blank=True, null=True, verbose_name="toimitettu"),
                ),
                ("huomiot", models.TextField(blank=True, verbose_name="huomiot")),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoneuvo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kierrot",
                        to="autot.ajoneuvo",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "luonut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kierto",
                "verbose_name_plural": "kierrot",
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Kulu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tyyppi",
                    models.CharField(
                        choices=[
                            ("huutokauppamaksu", "Huutokauppamaksu"),
                            ("kuljetus", "Kuljetus"),
                            ("huolto", "Huolto"),
                            ("kunnostus", "Kunnostus / korjaus"),
                            ("pesu", "Pesu / preppaus"),
                            ("katsastus", "Katsastus"),
                            ("renkaat", "Renkaat"),
                            ("rekisterointi", "Rekisteröinti / verot"),
                            ("reklamaatio", "Reklamaatio / jälkikorjaus"),
                            ("hyvitys", "Hyvitys ostajalle"),
                            ("muu", "Muu"),
                        ],
                        default="muu",
                        max_length=30,
                        verbose_name="tyyppi",
                    ),
                ),
                (
                    "kuvaus",
                    models.CharField(blank=True, max_length=500, verbose_name="kuvaus"),
                ),
                (
                    "summa_veroton",
                    models.BigIntegerField(
                        help_text="senttiä", verbose_name="summa (alv 0)"
                    ),
                ),
                (
                    "alv_prosentti",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.5"),
                        max_digits=5,
                        verbose_name="ALV %",
                    ),
                ),
                (
                    "pvm",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="päivämäärä",
                    ),
                ),
                (
                    "toimittaja",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="toimittaja / korjaamo"
                    ),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kulut",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "luonut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kulu",
                "verbose_name_plural": "kulut",
                "ordering": ["pvm", "id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Kuva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avain", models.CharField(max_length=300)),
                (
                    "tyyppi",
                    models.CharField(
                        choices=[
                            ("ulko", "Ulkokuvat"),
                            ("sisa", "Sisäkuvat"),
                            ("vaurio", "Vauriot"),
                            ("dokumentti", "Dokumentit"),
                        ],
                        default="ulko",
                        max_length=20,
                    ),
                ),
                ("jarjestys", models.IntegerField(default=0)),
                ("paakuva", models.BooleanField(default=False)),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kuvat",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "luonut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kuva",
                "verbose_name_plural": "kuvat",
                "ordering": ["-paakuva", "tyyppi", "jarjestys", "id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Rengassarja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tyyppi",
                    models.CharField(
                        choices=[
                            ("kesa", "Kesä"),
                            ("kitka", "Kitka"),
                            ("nasta", "Nasta"),
                            ("ymparivuotinen", "Ympärivuotinen"),
                        ],
                        max_length=20,
                        verbose_name="tyyppi",
                    ),
                ),
                (
                    "koko",
                    models.CharField(blank=True, max_length=30, verbose_name="koko"),
                ),
                (
                    "vanteet",
                    models.CharField(
                        blank=True,
                        choices=[("pelti", "Pelti"), ("alumiini", "Alumiini")],
                        max_length=20,
                        verbose_name="vanteet",
                    ),
                ),
                (
                    "urasyvyys_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="urasyvyys (mm)",
                    ),
                ),
                (
                    "kunto",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="kunto (1–5)",
                    ),
                ),
                (
                    "sijainti",
                    models.CharField(
                        choices=[
                            ("alla", "Autossa alla"),
                            ("mukana", "Mukana"),
                            ("varastossa", "Varastossa"),
                        ],
                        default="alla",
                        max_length=20,
                        verbose_name="sijainti",
                    ),
                ),
                (
                    "huomiot",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="huomiot"
                    ),
                ),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rengassarjat",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "rengassarja",
                "verbose_name_plural": "rengassarjat",
                "ordering": ["id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tehtavapohja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tila",
                    models.CharField(
                        choices=[
                            ("tarjottu", "Tarjottu"),
                            ("ostettu", "Ostettu"),
                            ("tulossa", "Tulossa"),
                            ("kunnostuksessa", "Kunnostuksessa"),
                            ("myynnissa", "Myynnissä"),
                            ("varattu", "Varattu"),
                            ("myyty", "Myyty"),
                            ("toimitettu", "Toimitettu"),
                            ("hylatty", "Hylätty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("otsikko", models.CharField(max_length=200)),
                ("rooli", models.CharField(blank=True, max_length=20)),
                (
                    "erapaiva_pv",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("jarjestys", models.IntegerField(default=0)),
                ("aktiivinen", models.BooleanField(default=True)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "vastuu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tehtäväpohja",
                "verbose_name_plural": "tehtäväpohjat",
                "ordering": ["jarjestys", "id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tilahistoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vanha_tila",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarjottu", "Tarjottu"),
                            ("ostettu", "Ostettu"),
                            ("tulossa", "Tulossa"),
                            ("kunnostuksessa", "Kunnostuksessa"),
                            ("myynnissa", "Myynnissä"),
                            ("varattu", "Varattu"),
                            ("myyty", "Myyty"),
                            ("toimitettu", "Toimitettu"),
                            ("hylatty", "Hylätty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "uusi_tila",
                    models.CharField(
                        choices=[
                            ("tarjottu", "Tarjottu"),
                            ("ostettu", "Ostettu"),
                            ("tulossa", "Tulossa"),
                            ("kunnostuksessa", "Kunnostuksessa"),
                            ("myynnissa", "Myynnissä"),
                            ("varattu", "Varattu"),
                            ("myyty", "Myyty"),
                            ("toimitettu", "Toimitettu"),
                            ("hylatty", "Hylätty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aika", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kayttaja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tilahistoria",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "tilasiirto",
                "verbose_name_plural": "tilahistoria",
                "ordering": ["aika", "id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Varuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nimi", models.CharField(max_length=200)),
                ("aktiivinen", models.BooleanField(default=True)),
                ("jarjestys", models.IntegerField(default=0)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "varuste",
                "verbose_name_plural": "varusteet",
                "ordering": ["jarjestys", "nimi"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AjoneuvonVaruste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ajoneuvo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autot.ajoneuvo"
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "varuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autot.varuste"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="ajoneuvo",
            name="varusteet",
            field=models.ManyToManyField(
                blank=True,
                related_name="ajoneuvot",
                through="autot.AjoneuvonVaruste",
                to="autot.varuste",
            ),
        ),
        migrations.CreateModel(
            name="Varustekategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nimi", models.CharField(max_length=100)),
                ("jarjestys", models.IntegerField(default=0)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "varustekategoria",
                "verbose_name_plural": "varustekategoriat",
                "ordering": ["jarjestys", "nimi"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="varuste",
            name="kategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="varusteet",
                to="autot.varustekategoria",
            ),
        ),
        migrations.CreateModel(
            name="Vaurio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kohta", models.CharField(max_length=100, verbose_name="kohta")),
                (
                    "kuvaus",
                    models.CharField(blank=True, max_length=500, verbose_name="kuvaus"),
                ),
                (
                    "arvioitu_korjaus",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="arvioitu korjaus",
                    ),
                ),
                ("korjattu", models.BooleanField(default=False)),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vauriot",
                        to="autot.kierto",
                    ),
                ),
                (
                    "kuva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="autot.kuva",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaurio",
                "verbose_name_plural": "vauriot",
                "ordering": ["korjattu", "id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Yritys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nimi", models.CharField(max_length=200, verbose_name="nimi")),
                (
                    "y_tunnus",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Y-tunnus"
                    ),
                ),
                (
                    "tyyppi",
                    models.CharField(
                        choices=[
                            ("rahoitusyhtio", "Rahoitusyhtiö"),
                            ("huutokauppa", "Huutokauppa"),
                            ("autoliike", "Autoliike"),
                            ("yksityinen", "Yksityinen"),
                            ("muu", "Muu"),
                        ],
                        default="autoliike",
                        max_length=20,
                        verbose_name="tyyppi",
                    ),
                ),
                (
                    "yhteyshenkilo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="yhteyshenkilö"
                    ),
                ),
                (
                    "puhelin",
                    models.CharField(blank=True, max_length=50, verbose_name="puhelin"),
                ),
                (
                    "sahkoposti",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="sähköposti"
                    ),
                ),
                ("huomiot", models.TextField(blank=True, verbose_name="huomiot")),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "yritys",
                "verbose_name_plural": "yritykset",
                "ordering": ["nimi"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="kierto",
            name="asiakas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="myynnit",
                to="autot.yritys",
                verbose_name="ostaja",
            ),
        ),
        migrations.AddField(
            model_name="kierto",
            name="toimittaja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ostot",
                to="autot.yritys",
                verbose_name="toimittaja",
            ),
        ),
        migrations.CreateModel(
            name="Koodi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ryhma",
                    models.CharField(
                        choices=[
                            ("kayttovoima", "Käyttövoima"),
                            ("vaihteisto", "Vaihteisto"),
                            ("korimalli", "Korimalli"),
                        ],
                        max_length=20,
                    ),
                ),
                ("koodi", models.CharField(max_length=10)),
                ("nimi", models.CharField(max_length=100)),
                ("jarjestys", models.IntegerField(default=0)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "koodi",
                "verbose_name_plural": "koodit",
                "ordering": ["ryhma", "jarjestys", "nimi"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liike", "ryhma", "koodi"), name="koodi_uniikki"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Kuntoraportti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaihe",
                    models.CharField(
                        choices=[
                            ("tarjous", "Tarjousvaihe"),
                            ("saapuminen", "Saapumistarkastus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tuulilasi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ehja", "Ehjä"),
                            ("kiveniskuja", "Kiveniskuja"),
                            ("vaihdettava", "Vaihdettava"),
                        ],
                        max_length=20,
                        verbose_name="tuulilasi",
                    ),
                ),
                (
                    "avaimet",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="avaimet (kpl)"
                    ),
                ),
                (
                    "maalipinta",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="maalipinta (1–5)",
                    ),
                ),
                (
                    "yleiskunto",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="yleiskunto (1–5)",
                    ),
                ),
                (
                    "sisatilat",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="sisätilat (1–5)",
                    ),
                ),
                (
                    "huoltokirja",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("taysi", "Täysi"),
                            ("osittainen", "Osittainen"),
                            ("puuttuu", "Puuttuu"),
                        ],
                        max_length=20,
                        verbose_name="huoltohistoria",
                    ),
                ),
                ("huomiot", models.TextField(blank=True, verbose_name="huomiot")),
                ("paivitetty", models.DateTimeField(auto_now=True)),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kuntoraportit",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "tehnyt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "kuntoraportti",
                "verbose_name_plural": "kuntoraportit",
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kierto", "vaihe"), name="kuntoraportti_vaihe_uniikki"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Muutosloki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kohde", models.CharField(max_length=20)),
                ("kohde_id", models.BigIntegerField()),
                ("kentta", models.CharField(max_length=100)),
                ("vanha", models.TextField(blank=True)),
                ("uusi", models.TextField(blank=True)),
                ("aika", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kayttaja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
            ],
            options={
                "verbose_name": "muutos",
                "verbose_name_plural": "muutosloki",
                "ordering": ["-aika", "-id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["kohde", "kohde_id"], name="muutosloki_kohde_idx"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tehtava",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tila_vaihe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tarjottu", "Tarjottu"),
                            ("ostettu", "Ostettu"),
                            ("tulossa", "Tulossa"),
                            ("kunnostuksessa", "Kunnostuksessa"),
                            ("myynnissa", "Myynnissä"),
                            ("varattu", "Varattu"),
                            ("myyty", "Myyty"),
                            ("toimitettu", "Toimitettu"),
                            ("hylatty", "Hylätty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("otsikko", models.CharField(max_length=200, verbose_name="tehtävä")),
                (
                    "kuvaus",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="lisätiedot"
                    ),
                ),
                ("rooli", models.CharField(blank=True, max_length=20)),
                (
                    "erapaiva",
                    models.DateField(blank=True, null=True, verbose_name="eräpäivä"),
                ),
                ("tehty", models.BooleanField(default=False)),
                ("tehty_aika", models.DateTimeField(blank=True, null=True)),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tehtavat",
                        to="autot.kierto",
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "luonut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tehnyt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vastuu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vastuuhenkilö",
                    ),
                ),
            ],
            options={
                "verbose_name": "tehtävä",
                "verbose_name_plural": "tehtävät",
                "ordering": [
                    "tehty",
                    models.OrderBy(models.F("erapaiva"), nulls_last=True),
                    "id",
                ],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["liike", "vastuu", "tehty"], name="tehtava_vastuu_idx"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="ajoneuvonvaruste",
            constraint=models.UniqueConstraint(
                fields=("ajoneuvo", "varuste"), name="ajoneuvon_varuste_uniikki"
            ),
        ),
        migrations.AddIndex(
            model_name="ajoneuvo",
            index=models.Index(
                fields=["liike", "rekisterinumero"], name="ajoneuvo_rek_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ajoneuvo",
            index=models.Index(fields=["liike", "vin"], name="ajoneuvo_vin_idx"),
        ),
        migrations.AddIndex(
            model_name="kierto",
            index=models.Index(fields=["liike", "tila"], name="kierto_liike_tila_idx"),
        ),
        migrations.AddConstraint(
            model_name="kierto",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("tila__in", ["myyty", "toimitettu", "hylatty"]), _negated=True
                ),
                fields=("ajoneuvo",),
                name="yksi_avoin_kierto_per_ajoneuvo",
            ),
        ),
    ]
