# Generated by Django 5.2.17 on 2026-09-28 09:00

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0003_kulu_summa_verollinen_pakollinen"),
        ("liikkeet", "0003_liike_yhteystiedot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sopimus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tyyppi",
                    models.CharField(
                        choices=[("osto", "Ostosopimus"), ("myynti", "Myyntisopimus")],
                        max_length=10,
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="sopimusnumero")),
                (
                    "pvm",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="päiväys"
                    ),
                ),
                ("vp_nimi", models.CharField(max_length=200, verbose_name="nimi")),
                (
                    "vp_tunnus",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Y-tunnus / henkilötunnus",
                    ),
                ),
                (
                    "vp_lahiosoite",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="lähiosoite"
                    ),
                ),
                (
                    "vp_postinumero",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="postinumero"
                    ),
                ),
                (
                    "vp_postitoimipaikka",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="postitoimipaikka"
                    ),
                ),
                (
                    "vp_puhelin",
                    models.CharField(blank=True, max_length=50, verbose_name="puhelin"),
                ),
                (
                    "vp_sahkoposti",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="sähköposti"
                    ),
                ),
                (
                    "vp_tilinumero",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="tilinumero (IBAN)"
                    ),
                ),
                (
                    "vp_alv_velvollinen",
                    models.BooleanField(default=False, verbose_name="alv-velvollinen"),
                ),
                (
                    "vp2_nimi",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="toisen osapuolen nimi"
                    ),
                ),
                (
                    "vp2_tunnus",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="toisen osapuolen Y-tunnus / henkilötunnus",
                    ),
                ),
                (
                    "vp2_osoite",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="toisen osapuolen osoite",
                    ),
                ),
                (
                    "vp2_puhelin",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="toisen osapuolen puhelin",
                    ),
                ),
                (
                    "vp2_sahkoposti",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="toisen osapuolen sähköposti",
                    ),
                ),
                (
                    "tunnistus",
                    models.CharField(
                        choices=[
                            ("ajokortti", "Ajokortti"),
                            ("passi", "Passi"),
                            ("henkilokortti", "Henkilökortti"),
                            ("muu", "Muu"),
                            ("ei", "Ei tarkastettu (yritys)"),
                        ],
                        default="ei",
                        max_length=20,
                        verbose_name="henkilötiedot tarkastettu",
                    ),
                ),
                (
                    "pep",
                    models.BooleanField(
                        default=False,
                        verbose_name="poliittisesti vaikutusvaltainen henkilö (PEP)",
                    ),
                ),
                (
                    "toimitusaika",
                    models.DateField(
                        blank=True, null=True, verbose_name="toimitusaika"
                    ),
                ),
                (
                    "maksutapa",
                    models.CharField(
                        choices=[
                            ("tilisiirto", "Tilisiirto"),
                            ("lasku", "Lasku"),
                            ("kateinen", "Käteinen"),
                            ("rahoitus", "Osamaksu / rahoitus"),
                            ("muu", "Muu"),
                        ],
                        default="tilisiirto",
                        max_length=20,
                        verbose_name="maksutapa",
                    ),
                ),
                (
                    "toimistokulut",
                    models.BigIntegerField(
                        default=0, help_text="senttiä", verbose_name="toimistokulut"
                    ),
                ),
                (
                    "etumaksu",
                    models.BigIntegerField(
                        default=0, help_text="senttiä", verbose_name="etumaksu"
                    ),
                ),
                (
                    "rahoitettava",
                    models.BigIntegerField(
                        default=0,
                        help_text="senttiä",
                        verbose_name="rahoitettava osuus",
                    ),
                ),
                (
                    "rahoitusyhtio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="rahoitusyhtiö"
                    ),
                ),
                (
                    "erapaiva",
                    models.DateField(
                        blank=True, null=True, verbose_name="laskun eräpäivä"
                    ),
                ),
                (
                    "lisatiedot",
                    models.TextField(
                        blank=True, verbose_name="lisätiedot ja muut ehdot"
                    ),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "sopimus",
                "verbose_name_plural": "sopimukset",
                "ordering": ["-pvm", "-numero"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SopimusRivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rooli",
                    models.CharField(
                        choices=[
                            ("kohde", "Kaupan kohde"),
                            ("vaihto", "Vaihtoajoneuvo"),
                        ],
                        default="kohde",
                        max_length=10,
                    ),
                ),
                (
                    "hinta",
                    models.BigIntegerField(
                        help_text="senttiä, sis. mahdollisen alv:n",
                        verbose_name="käteishinta",
                    ),
                ),
                (
                    "jaannosvelka",
                    models.BigIntegerField(
                        default=0, help_text="senttiä", verbose_name="jäännösvelka"
                    ),
                ),
                (
                    "jaannosvelan_haltija",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="jäännösvelan haltija"
                    ),
                ),
                (
                    "alv_kasittely",
                    models.CharField(
                        choices=[
                            ("marginaali", "Marginaaliverotus"),
                            ("alv", "Normaali ALV"),
                        ],
                        default="marginaali",
                        max_length=20,
                        verbose_name="verotus",
                    ),
                ),
                ("rekisterinumero", models.CharField(blank=True, max_length=20)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("merkki_malli", models.CharField(max_length=300)),
                (
                    "km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="mittarilukema"
                    ),
                ),
                (
                    "ensirekisterointi",
                    models.DateField(
                        blank=True, null=True, verbose_name="ensirekisteröinti"
                    ),
                ),
                (
                    "katsastettu",
                    models.DateField(
                        blank=True, null=True, verbose_name="edellinen katsastus"
                    ),
                ),
                (
                    "kolaroitu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ei", "Ei"),
                            ("kylla", "Kyllä"),
                            ("ei_tietoa", "Ei tietoa"),
                        ],
                        max_length=10,
                        verbose_name="kolaroitu",
                    ),
                ),
                (
                    "maahantuotu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ei", "Ei"),
                            ("kylla", "Kyllä"),
                            ("ei_tietoa", "Ei tietoa"),
                        ],
                        max_length=10,
                        verbose_name="tuotu käytettynä maahan",
                    ),
                ),
                (
                    "mittari_vastaa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ei", "Ei"),
                            ("kylla", "Kyllä"),
                            ("ei_tietoa", "Ei tietoa"),
                        ],
                        max_length=10,
                        verbose_name="mittarilukema vastaa ajomäärää",
                    ),
                ),
                (
                    "rakennemuutoksia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ei", "Ei"),
                            ("kylla", "Kyllä"),
                            ("ei_tietoa", "Ei tietoa"),
                        ],
                        max_length=10,
                        verbose_name="rakenteellisia muutoksia",
                    ),
                ),
            ],
            options={
                "verbose_name": "sopimusrivi",
                "verbose_name_plural": "sopimusrivit",
                "ordering": ["id"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="yritys",
            name="alv_velvollinen",
            field=models.BooleanField(default=False, verbose_name="alv-velvollinen"),
        ),
        migrations.AddField(
            model_name="yritys",
            name="lahiosoite",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="lähiosoite"
            ),
        ),
        migrations.AddField(
            model_name="yritys",
            name="postinumero",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="postinumero"
            ),
        ),
        migrations.AddField(
            model_name="yritys",
            name="postitoimipaikka",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="postitoimipaikka"
            ),
        ),
        migrations.AddField(
            model_name="yritys",
            name="tilinumero",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="tilinumero (IBAN)"
            ),
        ),
        migrations.AlterField(
            model_name="kierto",
            name="ostokanava",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rahoitusyhtio", "Rahoitusyhtiö"),
                    ("huutokauppa", "Huutokauppa"),
                    ("autoliike", "Autoliike"),
                    ("yksityinen", "Yksityinen"),
                    ("muu", "Muu"),
                    ("vaihto", "Vaihtoauto"),
                ],
                max_length=20,
                verbose_name="ostokanava",
            ),
        ),
        migrations.AlterField(
            model_name="yritys",
            name="y_tunnus",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Y-tunnus / henkilötunnus"
            ),
        ),
        migrations.AddConstraint(
            model_name="kierto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "tila__in",
                            [
                                "ostettu",
                                "tulossa",
                                "kunnostuksessa",
                                "myynnissa",
                                "varattu",
                                "myyty",
                                "toimitettu",
                            ],
                        ),
                        _negated=True,
                    ),
                    ("ostohinta__isnull", False),
                    _connector="OR",
                ),
                name="ostetulla_autolla_ostohinta",
                violation_error_message="Varastossa olevalla autolla pitää olla ostohinta.",
            ),
        ),
        migrations.AddConstraint(
            model_name="kierto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tila__in", ["myyty", "toimitettu"]), _negated=True),
                    ("myyntihinta__isnull", False),
                    _connector="OR",
                ),
                name="myydylla_autolla_myyntihinta",
                violation_error_message="Myydyllä autolla pitää olla myyntihinta.",
            ),
        ),
        migrations.AddField(
            model_name="sopimus",
            name="laatija",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sopimus",
            name="liike",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="liikkeet.liike",
            ),
        ),
        migrations.AddField(
            model_name="sopimus",
            name="vastapuoli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sopimukset",
                to="autot.yritys",
            ),
        ),
        migrations.AddField(
            model_name="sopimusrivi",
            name="kierto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sopimusrivit",
                to="autot.kierto",
            ),
        ),
        migrations.AddField(
            model_name="sopimusrivi",
            name="liike",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="liikkeet.liike",
            ),
        ),
        migrations.AddField(
            model_name="sopimusrivi",
            name="sopimus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rivit",
                to="autot.sopimus",
            ),
        ),
        migrations.AddConstraint(
            model_name="sopimus",
            constraint=models.UniqueConstraint(
                fields=("liike", "numero"), name="sopimusnumero_uniikki"
            ),
        ),
    ]
