# Generated by Django 5.2.17 on 2026-09-28 13:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0005_kuva_paikka"),
        ("liikkeet", "0004_liike_menettely_maksuaika"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lasku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suunta",
                    models.CharField(
                        choices=[("myynti", "Myyntilasku"), ("osto", "Ostolasku")],
                        max_length=10,
                    ),
                ),
                (
                    "laji",
                    models.CharField(
                        choices=[
                            ("etumaksu", "Käsiraha (etumaksu)"),
                            ("rahoitus", "Rahoitusyhtiön osuus"),
                            ("toimitus", "Maksu toimitettaessa"),
                            ("vaihtoauto", "Maksettu vaihtoajoneuvolla"),
                            ("hyvitys", "Hyvitys asiakkaalle"),
                            ("ostohinta", "Ostohinta myyjälle"),
                            ("jaannosvelka", "Jäännösvelka rahoittajalle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="laskunumero")),
                (
                    "viitenumero",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="viitenumero"
                    ),
                ),
                (
                    "pvm",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="laskun päiväys",
                    ),
                ),
                (
                    "erapaiva",
                    models.DateField(blank=True, null=True, verbose_name="eräpäivä"),
                ),
                (
                    "osapuoli_nimi",
                    models.CharField(max_length=200, verbose_name="nimi"),
                ),
                (
                    "osapuoli_tunnus",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Y-tunnus / henkilötunnus",
                    ),
                ),
                (
                    "osapuoli_osoite",
                    models.CharField(blank=True, max_length=300, verbose_name="osoite"),
                ),
                (
                    "tilinumero",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="maksetaan tilille"
                    ),
                ),
                (
                    "summa",
                    models.BigIntegerField(help_text="senttiä", verbose_name="summa"),
                ),
                ("kuvaus", models.CharField(max_length=500, verbose_name="kuvaus")),
                (
                    "maksettu_pvm",
                    models.DateField(blank=True, null=True, verbose_name="maksettu"),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "sopimus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="laskut",
                        to="autot.sopimus",
                    ),
                ),
            ],
            options={
                "verbose_name": "lasku",
                "verbose_name_plural": "laskut",
                "ordering": ["-pvm", "-numero"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liike", "suunta", "numero"), name="laskunumero_uniikki"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Myyntitarjous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="tarjousnumero")),
                (
                    "pvm",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="päiväys"
                    ),
                ),
                (
                    "voimassa",
                    models.DateField(
                        blank=True, null=True, verbose_name="voimassa asti"
                    ),
                ),
                (
                    "vp_nimi",
                    models.CharField(max_length=200, verbose_name="asiakkaan nimi"),
                ),
                (
                    "vp_puhelin",
                    models.CharField(blank=True, max_length=50, verbose_name="puhelin"),
                ),
                (
                    "vp_sahkoposti",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="sähköposti"
                    ),
                ),
                (
                    "hinta",
                    models.BigIntegerField(
                        help_text="senttiä, sis. mahdollisen alv:n",
                        verbose_name="käteishinta",
                    ),
                ),
                (
                    "toimistokulut",
                    models.BigIntegerField(
                        default=0, help_text="senttiä", verbose_name="toimistokulut"
                    ),
                ),
                (
                    "vaihto_rekisterinumero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="vaihtoauton rekisterinumero",
                    ),
                ),
                (
                    "vaihto_merkki",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="vaihtoauton merkki"
                    ),
                ),
                (
                    "vaihto_malli",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="vaihtoauton malli"
                    ),
                ),
                (
                    "vaihto_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="vaihtoauton mittarilukema"
                    ),
                ),
                (
                    "vaihto_hinta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="senttiä",
                        null=True,
                        verbose_name="vaihtohinta",
                    ),
                ),
                (
                    "vaihto_jaannosvelka",
                    models.BigIntegerField(
                        default=0,
                        help_text="senttiä",
                        verbose_name="vaihtoauton jäännösvelka",
                    ),
                ),
                ("lisatiedot", models.TextField(blank=True, verbose_name="lisätiedot")),
                (
                    "tila",
                    models.CharField(
                        choices=[
                            ("avoin", "Avoin"),
                            ("hyvaksytty", "Hyväksytty"),
                            ("hylatty", "Hylätty"),
                        ],
                        default="avoin",
                        max_length=20,
                    ),
                ),
                ("luotu", models.DateTimeField(auto_now_add=True)),
                (
                    "asiakas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="myyntitarjoukset",
                        to="autot.yritys",
                        verbose_name="asiakas rekisteristä",
                    ),
                ),
                (
                    "kierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myyntitarjoukset",
                        to="autot.kierto",
                    ),
                ),
                (
                    "laatija",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liike",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="liikkeet.liike",
                    ),
                ),
                (
                    "sopimus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="autot.sopimus",
                    ),
                ),
            ],
            options={
                "verbose_name": "myyntitarjous",
                "verbose_name_plural": "myyntitarjoukset",
                "ordering": ["-pvm", "-numero"],
                "abstract": False,
                "base_manager_name": "kaikki",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liike", "numero"), name="myyntitarjous_numero_uniikki"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("kaikki", django.db.models.manager.Manager()),
            ],
        ),
    ]
